CREATE TYPE "userRoles" AS ENUM (
  'administrator',
  'projectManager',
  'worker',
  'collaborator',
  'contributor'
);

CREATE TYPE "groupType" AS ENUM (
  'team',
  'organization',
  'committee',
  'personalGroup'
);

CREATE TYPE "taskStatus" AS ENUM (
  'pendingAssignment',
  'inProgress',
  'blocked',
  'completed'
);

CREATE TYPE "projectStatus" AS ENUM (
  'active',
  'archived',
  'onHold'
);

CREATE TYPE "priority" AS ENUM (
  'low',
  'medium',
  'high',
  'critical'
);

CREATE TYPE "visibility" AS ENUM (
  'public',
  'private'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "passwordHash" varchar NOT NULL,
  "firstName" varchar,
  "lastName" varchar,
  "role" "userRoles" DEFAULT 'worker',
  "createdAt" timestamp DEFAULT (now()),
  "avatar" bytea,
  "lastLogin" timestamp
);

CREATE TABLE "groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "type" "groupType" NOT NULL DEFAULT 'team',
  "ownerId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text,
  "startDate" date,
  "dueDate" date,
  "status" "projectStatus" DEFAULT 'active',
  "priority" priority DEFAULT 'medium',
  "ownerId" integer NOT NULL,
  "owningGroupId" integer,
  "visibility" visibility DEFAULT 'public',
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "projectId" integer NOT NULL,
  "assignedToUserId" integer,
  "status" "taskStatus" DEFAULT 'pendingAssignment',
  "priority" priority DEFAULT 'medium',
  "dueDate" date,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp
);

CREATE TABLE "userGroups" (
  "userId" integer NOT NULL,
  "groupId" integer NOT NULL,
  PRIMARY KEY ("userId", "groupId")
);

CREATE TABLE "userProjects" (
  "userId" integer NOT NULL,
  "projectId" integer NOT NULL,
  "joinDate" timestamp DEFAULT (now()),
  PRIMARY KEY ("userId", "projectId")
);

CREATE TABLE "projectPermissions" (
  "userId" integer NOT NULL,
  "projectId" integer NOT NULL,
  "projectRole" "userRoles" NOT NULL DEFAULT 'worker',
  PRIMARY KEY ("userId", "projectId")
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "taskId" integer NOT NULL,
  "userId" integer NOT NULL,
  "parentCommentId" integer,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "taskTags" (
  "taskId" integer NOT NULL,
  "tagId" integer NOT NULL,
  PRIMARY KEY ("taskId", "tagId")
);

COMMENT ON COLUMN "users"."passwordHash" IS 'Store securely';
COMMENT ON COLUMN "users"."role" IS 'Global system role';
COMMENT ON COLUMN "groups"."type" IS 'e.g., Team, Organization, Personal Group';
COMMENT ON COLUMN "groups"."ownerId" IS 'User who created/manages the group';
COMMENT ON COLUMN "projects"."ownerId" IS 'Individual user who created the project';
COMMENT ON COLUMN "projects"."owningGroupId" IS 'The organization or team officially sponsoring/owning the project';
COMMENT ON COLUMN "tasks"."assignedToUserId" IS 'Can be NULL if status is pendingAssignment';
COMMENT ON COLUMN "projectPermissions"."projectRole" IS 'Overrides global role for this project';
COMMENT ON COLUMN "comments"."taskId" IS 'Comment belongs to a task';
COMMENT ON COLUMN "comments"."userId" IS 'User who made the comment';
COMMENT ON COLUMN "comments"."parentCommentId" IS 'Self-reference for thread replies. NULL for top-level comments.';

ALTER TABLE "groups" ADD FOREIGN KEY ("ownerId") REFERENCES "users" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("ownerId") REFERENCES "users" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("owningGroupId") REFERENCES "groups" ("id");
ALTER TABLE "tasks" ADD FOREIGN KEY ("projectId") REFERENCES "projects" ("id");
ALTER TABLE "tasks" ADD FOREIGN KEY ("assignedToUserId") REFERENCES "users" ("id");
ALTER TABLE "userGroups" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "userGroups" ADD FOREIGN KEY ("groupId") REFERENCES "groups" ("id");
ALTER TABLE "userProjects" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "userProjects" ADD FOREIGN KEY ("projectId") REFERENCES "projects" ("id");
ALTER TABLE "projectPermissions" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "projectPermissions" ADD FOREIGN KEY ("projectId") REFERENCES "projects" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("taskId") REFERENCES "tasks" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("parentCommentId") REFERENCES "comments" ("id");
ALTER TABLE "taskTags" ADD FOREIGN KEY ("taskId") REFERENCES "tasks" ("id");
ALTER TABLE "taskTags" ADD FOREIGN KEY ("tagId") REFERENCES "tags" ("id");